version: "3.1"
services:
  git:
    image: gogs/gogs:0.11.86
    volumes:
      - ./app.ini:/data/gogs/conf/app.ini
      - ./data:/data
      - ./log:/app/gogs/log
    links:
      - mariadb
  mariadb:
    image: mariadb
    volumes:
      - ./mariadb-data:/var/lib/mysql
    env_file:
      # .env should contain MYSQL_ROOT_PASSWORD for root password
      - ./.env
